// Counting the number of packets in pcap files. 

// User defined package 
package labb; 

import java.io.File; 
import org.jnetpcap.Pcap; 
import org.jnetpcap.packet.JPacket; 
import org.jnetpcap.packet.JPacketHandler; 

public class la { 

	// Path of the folder having pcap files 
	// generated by Wireshark(change accordingly) 
	static String folderpath 
		= "/home/cse/Desktop/ns-allinone-3.28/pcap/"; 

	static double count = 0; 
	static double globalcount = 0; 

	// main function starts here 
	public static void main(String[] args) 
	{ 

		// Making the object of a file 
		// and giving that object address 
		// of the pcap folder 
		File file = new File(folderpath); 

		// Making file array which is used 
		// to access each file 
		// inside the folder one-by-one 
		File[] files = file.listFiles(); 

		// Accessing each file 
		// one-by-one of files array 
		for (File f : files) { 

			// Getting each pcap file name 
			String FILENAME 
				= folderpath + f.getName(); 

			// StringBuilder is used to get 
			// error messages in case 
			// if any error occurs 
			StringBuilder errbuf = new StringBuilder(); 

			// Making Pcap object an opening pcap file 
			// in offline mode and passing pcap filename 
			// and StringBuilder object to the function 
			Pcap pcap = Pcap.openOffline(FILENAME, errbuf); 

			// Here pcap object is used to start a loop 
			// for capturing each packet of an 
			// each pcap file(as a pcap file can 
			// have many packets) one at a time, here -1 
			// indicates eof(end of file) i.e 
			// until every packet is captured execute the 
			// loop, we can also give some value 
			// instead of -1 which will indicate the 
			// number of packets to execute 
			// in each pcap file 

			pcap.loop(-1, new JPacketHandler<StringBuilder>() { 

				// nextPacket is override function 
				// of JPacketHandler( Handler which is 
				// use to receive fully decoded packets) 
				public void nextPacket(JPacket packet, 
									StringBuilder errbuf) 
				{ 

					// counter to count the number of packet 
					// in each pcap file 
					count++; 
				} 
			}, errbuf); 

			System.out.println("File : " + f.getName() 
							+ " Number of Packets : "
							+ count); 

			// Global counter to count the total number 
			// of packets in all pcap file 
			globalcount = globalcount + count; 

			count = 0; 
		} 

		System.out.println("Total Packets in folder : "
						+ globalcount); 
	} 
} 
